export const GET_PROJECTS = 'GET_PROJECTS';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const OPEN_PROJECT_MODAL = 'OPEN_PROJECT_MODAL';
export const CLOSE_PROJECT_MODAL = 'CLOSE_PROJECT_MODAL';
export const CREATE_NEW_PROJECT = 'CREATE_NEW_PROJECT';

export const GET_FILES = 'GET_FILES';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const CREATE_NEW_FILE = 'CREATE_NEW_FILE';
export const DELETE_FILE = 'DELETE_FILE';
